export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Onboarding: undefined;
  UserRoleSelection: undefined;
  CustomerLogin: undefined;
  CustomerSignup: undefined;
  ShopperLogin: undefined;
  ShopperSignup: undefined;
  StoreOwnerLogin: undefined;
  StoreOwnerSignup: undefined;
  CustomerHome: undefined;
  ShopperHome: undefined;
  CustomerTabs: undefined;
  ShopperTabs: undefined;
  StoreOwnerHome: undefined;
  AddProduct: undefined;
  Restock: undefined;
  AllStores: undefined;
  StoreBrowse: { store: any };
  UserPreferences: undefined;
  Notifications: undefined;
  HelpCenter: undefined;
  Wishlist: undefined;
  Search: { initialQuery?: string } | undefined;
  Deals: undefined;
  LoyaltyPoints: undefined;
  Referral: undefined;
  ManageAddresses: { addresses: any[] };
  PaymentMethods: undefined;
  ProductDetails: { product: any };
  CartCheckout: undefined;
  Checkout: undefined;
  Orders: undefined;
  OrderTracking: { order: any };
  EditProfile: undefined;
  Profile: undefined;
  ShopperChat: undefined;
};


